title: Guillermo Calvo
email: cv@guillermo.dev
description: Guillermo Calvo - Curriculum Vitae.
baseurl:
url: https://guillermo.dev
repository: guillermocalvo/guillermocalvo.github.io
markdown: kramdown
include:
  - _redirects
